require 'test/unit'
require 'bukkit'

class TestInstall < Test::Unit::TestCase
	def test_install
		plugin = Bukkit::Plugin.new("WorldEdit")
		
		# Go into server's dir.
		Dir.chdir("my-awesome-server")
		# Create plugins dir because it isn't generated by tests.
		Dir.mkdir("plugins") unless Dir.exists?("plugins")
		plugin.install

		expected = File.exists?("WorldEdit.jar")
		assert_equal(expected, true)
		Dir.chdir("../")

		# Then delete it again and cd back out.
		FileUtils.rm_rf("plugins")
		Dir.chdir("../")
	end
end